name: Test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Git
      uses: actions/checkout@v4

    - name: Checkout Library - java-utilities
      uses: actions/checkout@v4
      with:
        repository: derBobby/java-utilities
        ref: main
        path: java-utilities

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install Library - java-utilities
      working-directory: ${{ github.workspace }}/java-utilities
      run: |
        mvn clean install

    - name: Build with Maven
      run: mvn -B package -PTEST --file pom.xml